# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/postgraduateStudy/graduation_thesis/SeaFog-DetSys/nc
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math


seafog:
  detection:
    pythonApi: http://localhost:5000
  upload:
    path: E:/postgraduateStudy/graduation_thesis/SeaFog-DetSys/nc
  himawari:
    username: 2046766443_qq.com    # 完整的用户名
    password: SP+wari8          # FTP密码
    download-timeout: 300       # 下载超时时间（秒）
    retry-attempts: 3           # 重试次数
  image:
    temp-path: E:/postgraduateStudy/graduation_thesis/SeaFog-DetSys/nc   # 临时文件存储路径
    netcdf-path: ${seafog.image.temp-path}/netcdf    # NC文件存储路径
    true-color-path: ${seafog.image.temp-path}/true-color    # 真彩色图像路径
    false-color-path: ${seafog.image.temp-path}/false-color  # 假彩色图像路径


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # 连接超时时间
    connection-timeout: 1800s
    # 最大连接数
    max-connections: 20000
    # 最大线程数
    threads:
      max: 800
      min-spare: 100
    # 最大上传大小
    max-swallow-size: -1
    # 增加缓冲区大小
    max-http-form-post-size: 2048MB
    # 禁用URL自动解码
    relaxed-query-chars: [ ]
    relaxed-path-chars: [ ]
    # 连接数满后的排队数
    accept-count: 1000
    # 添加缓冲区配置
    max-http-header-size: 102400
    # 启用异步支持
    async-timeout: 1800000
    basedir: E:/postgraduateStudy/graduation_thesis/SeaFog-DetSys/nc/tmp


# 日志配置
logging:
  level:
    com.SeaFog: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 文件上传配置
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: -1
      # 设置总上传的文件大小
      max-request-size: -1
      # 临时文件目录
      location: E:/postgraduateStudy/graduation_thesis/SeaFog-DetSys/nc/temp
      # 启用延迟解析
      resolve-lazily: true
      # 启用文件上传
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 0
      # 启用严格的文件大小检查
#      max-request-size-strict: true
      #连接超时时间
#      connection-timeout: 1800s

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.SeaFog.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

himawari:
  baseUrl: http://example.com/api
  username: your_username
  password: your_password

flask:
  api:
    url: http://localhost:5000  # Flask API的URL地址